# Generated by Django 5.0.6 on 2024-05-09 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('version', models.IntegerField(verbose_name='Versión')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='RUT')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('created_by', models.CharField(max_length=50, verbose_name='Creado por')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='RUT')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('created_by', models.CharField(max_length=50, verbose_name='Creado por')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('created_by', models.CharField(max_length=50, verbose_name='Creado por')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.course', verbose_name='Curso')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.student', verbose_name='Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50, verbose_name='Calle')),
                ('number', models.CharField(max_length=10, verbose_name='Número')),
                ('dept', models.CharField(max_length=5, verbose_name='Departamento')),
                ('commune', models.CharField(max_length=50, verbose_name='Comuna')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('region', models.CharField(max_length=50, verbose_name='Estado')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.student', verbose_name='Estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.teacher', verbose_name='Profesor'),
        ),
    ]
