# Generated by Django 5.0.6 on 2024-05-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Actualizado el'),
        ),
    ]
