# Generated by Django 5.0.4 on 2024-05-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_vehicle_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingrecord',
            name='buy_date',
            field=models.DateField(verbose_name='Fecha de compra'),
        ),
    ]
